import { fileURLToPath } from 'node:url';

import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import pg from 'pg';

import type { Logger, Secret } from '@servicerouter/common';

// SQL generated by drizzle-kit (`npm run db:generate`). The folder ships in the image next to dist/.
export const migrationsFolder = fileURLToPath(new URL('../migrations', import.meta.url));

// Session-level advisory lock, so two runs against one database apply each migration once
const migrationLockId = 7_301_746_117;

export interface MigrateDatabaseOptions {
  // DATABASE_URL. It carries the password, so it stays in a Secret and is never logged.
  readonly url: Secret;
  readonly logger: Logger;
}

const countApplied = async (client: pg.Client): Promise<number> => {
  const { rows: [table] } = await client.query<{ name: string | null }>(`select to_regclass('drizzle.__drizzle_migrations')::text as name`);
  if (!table?.name)
    return 0;

  const { rows: [result] } = await client.query<{ count: number }>('select count(*)::int as count from drizzle.__drizzle_migrations');

  return result?.count ?? 0;
};

/**
 * Applies pending migrations and returns how many it applied. Running it again applies nothing. A
 * one-off command runs it before the apps roll; apps never migrate on boot (S1-D3).
 */
export const migrateDatabase = async ({ url, logger }: MigrateDatabaseOptions): Promise<number> => {
  const client = new pg.Client({ connectionString: url.expose() });
  client.on('error', error => logger.error({ error }, 'Postgres connection error'));
  await client.connect();
  try {
    await client.query('select pg_advisory_lock($1)', [migrationLockId]);
    const before = await countApplied(client);
    await migrate(drizzle({ client }), { migrationsFolder });
    const applied = await countApplied(client) - before;
    logger.info({ applied }, applied > 0 ? 'Applied migrations' : 'Migrations are up to date');

    return applied;
  }
  finally {
    // Ending the session releases the lock
    await client.end();
  }
};
